"""phase1 initial schema

Revision ID: a2b7e06fb0ad
Revises: 
Create Date: 2026-09-18 05:55:46.998443

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'a2b7e06fb0ad'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_run',
    sa.Column('analysis_id', sa.String(length=64), nullable=False),
    sa.Column('stock_code', sa.String(length=16), nullable=False),
    sa.Column('as_of', sa.DateTime(), nullable=False),
    sa.Column('horizon', sa.String(length=16), nullable=False),
    sa.Column('engines_requested_json', sa.JSON(), nullable=True),
    sa.Column('engines_completed_json', sa.JSON(), nullable=True),
    sa.Column('engines_failed_json', sa.JSON(), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('versions_json', sa.JSON(), nullable=True),
    sa.Column('warnings_json', sa.JSON(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('analysis_id')
    )
    with op.batch_alter_table('analysis_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_run_as_of'), ['as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_run_stock_code'), ['stock_code'], unique=False)

    op.create_table('backtest_experiment',
    sa.Column('experiment_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('factor_ids_json', sa.JSON(), nullable=True),
    sa.Column('logic', sa.String(length=16), nullable=False),
    sa.Column('universe_json', sa.JSON(), nullable=True),
    sa.Column('horizons_json', sa.JSON(), nullable=True),
    sa.Column('date_from', sa.Date(), nullable=True),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.Column('benchmark_code', sa.String(length=16), nullable=False),
    sa.Column('params_json', sa.JSON(), nullable=True),
    sa.Column('methodology', sa.Text(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('experiment_id')
    )
    with op.batch_alter_table('backtest_experiment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backtest_experiment_kind'), ['kind'], unique=False)

    op.create_table('chart_artifact',
    sa.Column('chart_id', sa.String(length=64), nullable=False),
    sa.Column('stock_code', sa.String(length=16), nullable=False),
    sa.Column('engine', sa.String(length=32), nullable=False),
    sa.Column('engine_version', sa.String(length=64), nullable=False),
    sa.Column('config_version', sa.String(length=32), nullable=False),
    sa.Column('birth_profile_version', sa.String(length=16), nullable=False),
    sa.Column('as_of', sa.DateTime(), nullable=False),
    sa.Column('input_json', sa.JSON(), nullable=True),
    sa.Column('raw_chart', sa.JSON(), nullable=True),
    sa.Column('assumptions_json', sa.JSON(), nullable=True),
    sa.Column('warnings_json', sa.JSON(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('chart_id')
    )
    with op.batch_alter_table('chart_artifact', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chart_artifact_as_of'), ['as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_chart_artifact_engine'), ['engine'], unique=False)
        batch_op.create_index('ix_chart_artifact_lookup', ['stock_code', 'engine', 'as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_chart_artifact_stock_code'), ['stock_code'], unique=False)

    op.create_table('classical_book',
    sa.Column('book_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('author', sa.String(length=64), nullable=False),
    sa.Column('dynasty', sa.String(length=32), nullable=False),
    sa.Column('domain', sa.String(length=24), nullable=False),
    sa.Column('school', sa.String(length=32), nullable=False),
    sa.Column('edition', sa.String(length=128), nullable=False),
    sa.Column('provenance', sa.Text(), nullable=False),
    sa.Column('license_status', sa.String(length=24), nullable=False),
    sa.Column('authority_weight', sa.Float(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('book_id')
    )
    with op.batch_alter_table('classical_book', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classical_book_domain'), ['domain'], unique=False)

    op.create_table('engine_run',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('engine_id', sa.String(length=32), nullable=False),
    sa.Column('engine_version', sa.String(length=64), nullable=False),
    sa.Column('config_version', sa.String(length=32), nullable=False),
    sa.Column('stock_code', sa.String(length=16), nullable=False),
    sa.Column('as_of', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('warnings_json', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('engine_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_engine_run_engine_id'), ['engine_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_engine_run_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_engine_run_stock_code'), ['stock_code'], unique=False)

    op.create_table('engine_version',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('engine_id', sa.String(length=32), nullable=False),
    sa.Column('engine_version', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('config_version', sa.String(length=32), nullable=False),
    sa.Column('third_party', sa.String(length=128), nullable=False),
    sa.Column('third_party_commit', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('engine_id', 'engine_version', name='uq_engine_version')
    )
    with op.batch_alter_table('engine_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_engine_version_engine_id'), ['engine_id'], unique=False)

    op.create_table('exchange_session_calendar',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exchange', sa.String(length=16), nullable=False),
    sa.Column('board', sa.String(length=32), nullable=False),
    sa.Column('session_name', sa.String(length=32), nullable=False),
    sa.Column('open_time', sa.String(length=8), nullable=False),
    sa.Column('close_time', sa.String(length=8), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange', 'board', 'session_name', 'effective_from', name='uq_exchange_session')
    )
    with op.batch_alter_table('exchange_session_calendar', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exchange_session_calendar_exchange'), ['exchange'], unique=False)
        batch_op.create_index('ix_exchange_session_lookup', ['exchange', 'board'], unique=False)

    op.create_table('factor_definition',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('factor_id', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('engine', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=24), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('computation', sa.Text(), nullable=False),
    sa.Column('raw_unit', sa.String(length=64), nullable=False),
    sa.Column('normalized_hint', sa.Text(), nullable=False),
    sa.Column('default_direction', sa.Integer(), nullable=False),
    sa.Column('rule_score_meaning', sa.Text(), nullable=False),
    sa.Column('rule_version', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('requires_json', sa.JSON(), nullable=True),
    sa.Column('tags_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factor_id', 'rule_version', name='uq_factor_def_version')
    )
    with op.batch_alter_table('factor_definition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_factor_definition_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_factor_definition_engine'), ['engine'], unique=False)
        batch_op.create_index(batch_op.f('ix_factor_definition_factor_id'), ['factor_id'], unique=False)

    op.create_table('factor_observation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('factor_id', sa.String(length=48), nullable=False),
    sa.Column('stock_code', sa.String(length=16), nullable=False),
    sa.Column('as_of', sa.DateTime(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=True),
    sa.Column('engine', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('raw_value_json', sa.JSON(), nullable=True),
    sa.Column('normalized_value', sa.Float(), nullable=True),
    sa.Column('direction', sa.Integer(), nullable=False),
    sa.Column('rule_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('availability', sa.String(length=16), nullable=False),
    sa.Column('rule_version', sa.String(length=16), nullable=False),
    sa.Column('engine_version', sa.String(length=64), nullable=False),
    sa.Column('config_version', sa.String(length=32), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('warnings_json', sa.JSON(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_code', 'as_of', 'factor_id', 'rule_version', name='uq_factor_obs')
    )
    with op.batch_alter_table('factor_observation', schema=None) as batch_op:
        batch_op.create_index('ix_factor_obs_code', ['stock_code', 'as_of'], unique=False)
        batch_op.create_index('ix_factor_obs_lookup', ['factor_id', 'as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_factor_observation_as_of'), ['as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_factor_observation_factor_id'), ['factor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_factor_observation_stock_code'), ['stock_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_factor_observation_trade_date'), ['trade_date'], unique=False)

    op.create_table('market_bar_daily',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_code', sa.String(length=16), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('turnover', sa.Float(), nullable=True),
    sa.Column('pct_change', sa.Float(), nullable=True),
    sa.Column('adjust', sa.String(length=8), nullable=False),
    sa.Column('is_benchmark', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('is_degraded', sa.Boolean(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_code', 'trade_date', 'adjust', name='uq_bar_daily')
    )
    with op.batch_alter_table('market_bar_daily', schema=None) as batch_op:
        batch_op.create_index('ix_bar_daily_code_date', ['stock_code', 'trade_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_bar_daily_is_benchmark'), ['is_benchmark'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_bar_daily_stock_code'), ['stock_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_bar_daily_trade_date'), ['trade_date'], unique=False)

    op.create_table('market_fetch_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_code', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('market_fetch_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_fetch_log_stock_code'), ['stock_code'], unique=False)

    op.create_table('stock_master',
    sa.Column('stock_code', sa.String(length=16), nullable=False),
    sa.Column('wind_code', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('exchange', sa.String(length=16), nullable=False),
    sa.Column('board', sa.String(length=32), nullable=False),
    sa.Column('industry', sa.String(length=64), nullable=False),
    sa.Column('listing_date', sa.Date(), nullable=True),
    sa.Column('total_market_cap', sa.Float(), nullable=True),
    sa.Column('circulating_market_cap', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('data_quality_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('stock_code')
    )
    with op.batch_alter_table('stock_master', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_master_exchange'), ['exchange'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_master_listing_date'), ['listing_date'], unique=False)

    op.create_table('backtest_result',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('experiment_id', sa.String(length=64), nullable=False),
    sa.Column('variant', sa.String(length=48), nullable=False),
    sa.Column('horizon', sa.Integer(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('up_rate', sa.Float(), nullable=True),
    sa.Column('excess_up_rate', sa.Float(), nullable=True),
    sa.Column('mean_return', sa.Float(), nullable=True),
    sa.Column('median_return', sa.Float(), nullable=True),
    sa.Column('std_return', sa.Float(), nullable=True),
    sa.Column('mean_excess_return', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('mean_max_return', sa.Float(), nullable=True),
    sa.Column('extra_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['backtest_experiment.experiment_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backtest_result', schema=None) as batch_op:
        batch_op.create_index('ix_backtest_result_exp', ['experiment_id', 'horizon'], unique=False)
        batch_op.create_index(batch_op.f('ix_backtest_result_experiment_id'), ['experiment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_backtest_result_variant'), ['variant'], unique=False)

    op.create_table('classical_entry',
    sa.Column('entry_id', sa.String(length=64), nullable=False),
    sa.Column('book_id', sa.String(length=64), nullable=False),
    sa.Column('book', sa.String(length=128), nullable=False),
    sa.Column('domain', sa.String(length=24), nullable=False),
    sa.Column('school', sa.String(length=32), nullable=False),
    sa.Column('chapter', sa.String(length=128), nullable=False),
    sa.Column('section', sa.String(length=128), nullable=False),
    sa.Column('topic_json', sa.JSON(), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('normalized_text', sa.Text(), nullable=False),
    sa.Column('modern_note', sa.Text(), nullable=False),
    sa.Column('commentary', sa.Text(), nullable=False),
    sa.Column('authority_weight', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=256), nullable=False),
    sa.Column('edition', sa.String(length=128), nullable=False),
    sa.Column('provenance', sa.Text(), nullable=False),
    sa.Column('license_status', sa.String(length=24), nullable=False),
    sa.Column('stance_hint', sa.String(length=16), nullable=False),
    sa.Column('applies_to_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['classical_book.book_id'], ),
    sa.PrimaryKeyConstraint('entry_id')
    )
    with op.batch_alter_table('classical_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classical_entry_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classical_entry_domain'), ['domain'], unique=False)
        batch_op.create_index('ix_classical_entry_domain_school', ['domain', 'school'], unique=False)

    op.create_table('stock_birth_profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_code', sa.String(length=16), nullable=False),
    sa.Column('exchange', sa.String(length=16), nullable=False),
    sa.Column('birth_basis', sa.String(length=32), nullable=False),
    sa.Column('birth_datetime', sa.DateTime(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('birth_profile_version', sa.String(length=16), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=True),
    sa.Column('assumptions_json', sa.JSON(), nullable=True),
    sa.Column('data_quality_json', sa.JSON(), nullable=True),
    sa.Column('variant_mode', sa.String(length=24), nullable=False),
    sa.Column('variant_note', sa.Text(), nullable=False),
    sa.Column('ipo_date', sa.Date(), nullable=True),
    sa.Column('company_foundation', sa.Date(), nullable=True),
    sa.Column('first_trade', sa.DateTime(), nullable=True),
    sa.Column('custom_datetime', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['stock_code'], ['stock_master.stock_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_code', 'birth_basis', 'birth_profile_version', name='uq_birth_profile_version')
    )
    with op.batch_alter_table('stock_birth_profile', schema=None) as batch_op:
        batch_op.create_index('ix_birth_profile_stock', ['stock_code', 'birth_basis'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_birth_profile_birth_datetime'), ['birth_datetime'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_birth_profile_stock_code'), ['stock_code'], unique=False)

    op.create_table('evidence_link',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('entry_id', sa.String(length=64), nullable=False),
    sa.Column('stance', sa.String(length=16), nullable=False),
    sa.Column('relevance', sa.Float(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['classical_entry.entry_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_link', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_link_entry_id'), ['entry_id'], unique=False)
        batch_op.create_index('ix_evidence_link_target', ['target_type', 'target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_link_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_link_target_type'), ['target_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence_link', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_link_target_type'))
        batch_op.drop_index(batch_op.f('ix_evidence_link_target_id'))
        batch_op.drop_index('ix_evidence_link_target')
        batch_op.drop_index(batch_op.f('ix_evidence_link_entry_id'))

    op.drop_table('evidence_link')
    with op.batch_alter_table('stock_birth_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_birth_profile_stock_code'))
        batch_op.drop_index(batch_op.f('ix_stock_birth_profile_birth_datetime'))
        batch_op.drop_index('ix_birth_profile_stock')

    op.drop_table('stock_birth_profile')
    with op.batch_alter_table('classical_entry', schema=None) as batch_op:
        batch_op.drop_index('ix_classical_entry_domain_school')
        batch_op.drop_index(batch_op.f('ix_classical_entry_domain'))
        batch_op.drop_index(batch_op.f('ix_classical_entry_book_id'))

    op.drop_table('classical_entry')
    with op.batch_alter_table('backtest_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backtest_result_variant'))
        batch_op.drop_index(batch_op.f('ix_backtest_result_experiment_id'))
        batch_op.drop_index('ix_backtest_result_exp')

    op.drop_table('backtest_result')
    with op.batch_alter_table('stock_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_master_listing_date'))
        batch_op.drop_index(batch_op.f('ix_stock_master_exchange'))

    op.drop_table('stock_master')
    with op.batch_alter_table('market_fetch_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_fetch_log_stock_code'))

    op.drop_table('market_fetch_log')
    with op.batch_alter_table('market_bar_daily', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_bar_daily_trade_date'))
        batch_op.drop_index(batch_op.f('ix_market_bar_daily_stock_code'))
        batch_op.drop_index(batch_op.f('ix_market_bar_daily_is_benchmark'))
        batch_op.drop_index('ix_bar_daily_code_date')

    op.drop_table('market_bar_daily')
    with op.batch_alter_table('factor_observation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_factor_observation_trade_date'))
        batch_op.drop_index(batch_op.f('ix_factor_observation_stock_code'))
        batch_op.drop_index(batch_op.f('ix_factor_observation_factor_id'))
        batch_op.drop_index(batch_op.f('ix_factor_observation_as_of'))
        batch_op.drop_index('ix_factor_obs_lookup')
        batch_op.drop_index('ix_factor_obs_code')

    op.drop_table('factor_observation')
    with op.batch_alter_table('factor_definition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_factor_definition_factor_id'))
        batch_op.drop_index(batch_op.f('ix_factor_definition_engine'))
        batch_op.drop_index(batch_op.f('ix_factor_definition_category'))

    op.drop_table('factor_definition')
    with op.batch_alter_table('exchange_session_calendar', schema=None) as batch_op:
        batch_op.drop_index('ix_exchange_session_lookup')
        batch_op.drop_index(batch_op.f('ix_exchange_session_calendar_exchange'))

    op.drop_table('exchange_session_calendar')
    with op.batch_alter_table('engine_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_engine_version_engine_id'))

    op.drop_table('engine_version')
    with op.batch_alter_table('engine_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_engine_run_stock_code'))
        batch_op.drop_index(batch_op.f('ix_engine_run_run_id'))
        batch_op.drop_index(batch_op.f('ix_engine_run_engine_id'))

    op.drop_table('engine_run')
    with op.batch_alter_table('classical_book', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classical_book_domain'))

    op.drop_table('classical_book')
    with op.batch_alter_table('chart_artifact', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chart_artifact_stock_code'))
        batch_op.drop_index('ix_chart_artifact_lookup')
        batch_op.drop_index(batch_op.f('ix_chart_artifact_engine'))
        batch_op.drop_index(batch_op.f('ix_chart_artifact_as_of'))

    op.drop_table('chart_artifact')
    with op.batch_alter_table('backtest_experiment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backtest_experiment_kind'))

    op.drop_table('backtest_experiment')
    with op.batch_alter_table('analysis_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_run_stock_code'))
        batch_op.drop_index(batch_op.f('ix_analysis_run_as_of'))

    op.drop_table('analysis_run')
    # ### end Alembic commands ###
