"""phase1_1 acceptance hardening: forward_label + updated_at

Revision ID: dadb21454a4b
Revises: a2b7e06fb0ad
Create Date: 2026-09-18 11:05:58.514490

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'dadb21454a4b'
down_revision: str | None = 'a2b7e06fb0ad'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forward_label',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_code', sa.String(length=16), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('ret_1d', sa.Float(), nullable=True),
    sa.Column('ret_5d', sa.Float(), nullable=True),
    sa.Column('ret_10d', sa.Float(), nullable=True),
    sa.Column('ret_20d', sa.Float(), nullable=True),
    sa.Column('ret_60d', sa.Float(), nullable=True),
    sa.Column('max_return_20d', sa.Float(), nullable=True),
    sa.Column('max_drawdown_20d', sa.Float(), nullable=True),
    sa.Column('bench_ret_20d', sa.Float(), nullable=True),
    sa.Column('excess_return_20d', sa.Float(), nullable=True),
    sa.Column('absolute_up_20d', sa.Boolean(), nullable=True),
    sa.Column('excess_up_20d', sa.Boolean(), nullable=True),
    sa.Column('strong_up_20d', sa.Boolean(), nullable=True),
    sa.Column('drawdown_controlled_up_20d', sa.Boolean(), nullable=True),
    sa.Column('benchmark_code', sa.String(length=16), nullable=False),
    sa.Column('horizon_available_json', sa.JSON(), nullable=True),
    sa.Column('extra_returns_json', sa.JSON(), nullable=True),
    sa.Column('label_source', sa.String(length=48), nullable=False),
    sa.Column('is_degraded', sa.Boolean(), nullable=False),
    sa.Column('data_snapshot', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_code', 'as_of', 'benchmark_code', 'label_source', name='uq_forward_label')
    )
    with op.batch_alter_table('forward_label', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forward_label_as_of'), ['as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_forward_label_is_degraded'), ['is_degraded'], unique=False)
        batch_op.create_index('ix_forward_label_stock', ['stock_code', 'as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_forward_label_stock_code'), ['stock_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_forward_label_trade_date'), ['trade_date'], unique=False)

    with op.batch_alter_table('analysis_run', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('backtest_experiment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('backtest_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('chart_artifact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('classical_book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('classical_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('engine_run', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('engine_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('evidence_link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('factor_observation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('market_bar_daily', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('market_fetch_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_fetch_log', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('market_bar_daily', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('factor_observation', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('evidence_link', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('engine_version', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('engine_run', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('classical_entry', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('classical_book', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('chart_artifact', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('backtest_result', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('backtest_experiment', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('analysis_run', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('forward_label', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forward_label_trade_date'))
        batch_op.drop_index(batch_op.f('ix_forward_label_stock_code'))
        batch_op.drop_index('ix_forward_label_stock')
        batch_op.drop_index(batch_op.f('ix_forward_label_is_degraded'))
        batch_op.drop_index(batch_op.f('ix_forward_label_as_of'))

    op.drop_table('forward_label')
    # ### end Alembic commands ###
